### PR TITLE
update series.order to series.sort_values()

### PR DESCRIPTION
**Pull request by siraj-samsudeen**

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
Yes, that would be more up-to-date and agree with modern Pandas documentation! Could you:

1. Carry the edit through to the rest of the file — I think `.order()` appears in several places?
2. Adjust the lines around it so that the visual columns are preserved?

Thanks!

**Comment by siraj-samsudeen** [comment]
sure Brandon - will do it and get back

**Comment by siraj-samsudeen** [comment]
Hi Brandon, I am new to GitHub. Not sure whether you got notified when I updated the file with the changes you have asked for. So, following up

**Comment by brandon-rhodes** [comment]
Yes, I did get a notification! But because of travel, it might be a week or two until I am able to perform code reviews. My guess, though, is that I will definitely review this by the end of the month.

**Comment by siraj-samsudeen** [comment]
No problem at all Brandon.
Kind Regards,
Siraj, Chennai.

**Comment by brandon-rhodes** [comment]
Thanks for bringing that file up to date!

**Comment by siraj-samsudeen** [comment]
Thanks to you Brandon for such a wonderful tutorial. And for keeping the
exercises current.
Kind Regards,
Siraj

**Pull request merged**
