### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sagarkar10**
Since some data files ask for authentication, I added alternate links for the same files.

### CODE REVIEW

**Comment by sagarkar10** [comment]
any follow up sir?

**Comment by brandon-rhodes** [comment]
No. I will, alas, not have time to try those downloads and verify the problem until sometime next week.

**Comment by brandon-rhodes** [comment]
When you say the site asked for authentication, was it your browser that demanded the password, or a traditional FTP client? I just tried several of the files, and was not asked for authentication from the standard `ftp.fu-berlin.de` download site — could the site have been down, or temporarily misconfigured, during the moment that you received the demand for a password?

I am not certain, long-term, about whether we should point users at `ftp.funet.fi` as our official alternative to the main site without any further text about usage of the site, as its `/pub/README` says:

```
      - When you are working over long distance links, do limit yourself
    to off hours.  When working between the USA and Finland, try it
    after 4 PM OUR time ( 10 AM Eastern USA time.)  And remember that
    we wake up 10 hours before California.
    We are at time zone  `UTC +2h' and in summer 'UTC +3h'
```

But maybe the volume of people using the tutorial is small enough that we will not be a serious component of their load?

I will try merging this, and we will see whether users ever report any problems. If problems with `ftp.fu-berlin.de` persist, then we might also want a U.S. mirror (if we can find one) since many users of the tutorial could probably download more quickly over a non-transatlantic connection.

**Comment by sagarkar10** [comment]
thanks

**Pull request merged**
